services:
  shop:
    build: ./shop
    ports:
      - "8084:8084"
    depends_on:
      - db
      - payments-api
      - redis-cache
      - keycloak
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/shop
      - SPRING_R2DBC_USERNAME=shop
      - SPRING_R2DBC_PASSWORD=shop
      - SPRING_DATA_R2DBC_REPOSITORIES_ENABLED=true
      - PAYMENTS_SERVER_URL=http://payments-api:8085
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT:6379
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db:5432/shop
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI=http://keycloak:8080/realms/master
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080

  db:
    image: postgres:17-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - PGUSER=shop
      - POSTGRES_PASSWORD=shop

  payments-api:
    build: ./payments-api
    depends_on:
      - keycloak
    ports:
      - "8085:8085"
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080/realms/master
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWT-SET-URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs

  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - "8083:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=./realm-export.json